# Generated by Django 4.2.6 on 2023-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_upp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
